*  LISTS ALL RECAL ORDERS WHICH HAVE NOT BEEN APPROVED BY CUSTOMER
*  FOR EMPLOYEES WHO CONTACT CUSTOMERS ABOUT RECALS

USE Precheck
set order to tag ORDER_NO

SELECT PRECHECK.ORDER_NO, PRECHECK.SERIAL_NUM, PRECHECK.DATE_RECVD,;
  PRECHECK.RECVD_FROM, PRECHECK.MODEL_NUM;
 FROM PRECHECK;
 WHERE PRECHECK.APPROVED < CTOD("01/01/70");
   AND DELETED() <> .T.;
 INTO CURSOR QUERY 

