
PROCEDURE POPULATE_ORDER
	PARAMETERS cCOID, cORDERNO, cQUOTENO
	
	SELECT ORDRSTAT
	APPEND BLANK	
	REPLACE co_id WITH cCOID
	REPLACE order_no WITH cOrderno
		
	STORE SYS(0) TO username
	username = LEFT(TRIM(username), 6)
	REPLACE user_name WITH username


SELECT COMPANY1
LOCATE FOR CO_ID = cCoid AND NOT DELETED()
	STORE SALES_ACCT TO SALES
	STORE SALES_SUB TO SALE_SUB
	STORE COMPANY1.TAX_CODE TO TAX_CD
	STORE COMPANY1.DISCOUNT TO DISC_CD
	STORE COMPANY1.QA_REQ TO QA_R
	STORE COMPANY1.CO_TERMS TO CTERMS
	STORE CO_NAME TO CONAME
	
	STORE S_ADDR1 TO SLINEONE
	STORE S_ADDR2 TO SLINETWO
	STORE S_CITY TO SCITY
	STORE S_STATE TO SSTATE
	STORE S_ZIP TO SZIP
	STORE S_COUNTRY TO SCOUNTRY
	STORE S_AREACODE TO SAREA
	STORE S_PHONE TO SPHONE
	STORE S_ATTN TO SATTN
	
	STORE B_ADDR1 TO BLINEONE
	STORE B_ADDR2 TO BLINETWO
	STORE B_CITY TO BCITY
	STORE B_STATE TO BSTATE
	STORE B_ZIP TO BZIP
	STORE B_COUNTRY TO BCOUNTRY
	STORE B_AREACODE TO BAREA
	STORE B_PHONE TO BPHONE
	STORE B_ATTN TO BATTN
	

SELECT ORDRSTAT
LOCATE FOR ALLTRIM(order_no) == ALLTRIM(cOrderno) AND ALLTRIM(co_id) == ALLTRIM(cCOID) AND NOT DELETED()
FOUND = FOUND()	
	REPLACE SALES_ACCT WITH SALES
	REPLACE SALES_SUB WITH SALE_SUB
	REPLACE CO_NAME WITH CONAME
	REPLACE ORDRSTAT.CO_NAME WITH CONAME
	REPLACE ORDRSTAT.ORD_DATE WITH DATE()
	REPLACE ORDRSTAT.ORDR_CODE WITH CTERMS
	REPLACE ORDRSTAT.DISC_CODE WITH DISC_CD
	REPLACE ORDRSTAT.QA_CODE WITH QA_R
	REPLACE ORDRSTAT.USER_NAME WITH USERNAME	

	REPLACE ORDRSTAT.ST_TYPE WITH "No Change"
	REPLACE ORDRSTAT.ST_ADDR1 WITH SLINEONE
	REPLACE ORDRSTAT.ST_ADDR2 WITH SLINETWO
	REPLACE ORDRSTAT.ST_CITY WITH SCITY
	REPLACE ORDRSTAT.ST_STATE WITH SSTATE
	REPLACE ORDRSTAT.ST_ZIP WITH SZIP
	REPLACE ORDRSTAT.ST_COUNTRY WITH SCOUNTRY
	REPLACE ORDRSTAT.ST_AREACD WITH SAREA
	REPLACE ORDRSTAT.ST_PHONE WITH SPHONE
	REPLACE ORDRSTAT.ST_ATTN WITH SATTN
		
SELECT SHIPPING
LOCATE FOR CO_ID = cCOID AND NOT DELETED()
	IF FOUND() THEN		
		STORE S_ADDR1 TO SLINEONE
		STORE S_ADDR2 TO SLINETWO
		STORE S_CITY TO SCITY
		STORE S_STATE TO SSTATE
		STORE S_ZIP TO SZIP
		STORE S_COUNTRY TO SCOUNTRY
		STORE S_AREACD TO SAREA
		STORE S_PHONE TO SPHONE
		STORE S_ATTN TO SATTN
	ENDIF

SELECT ORDRSTAT
LOCATE FOR ALLTRIM(order_no) == ALLTRIM(cOrderno) AND ALLTRIM(co_id) == ALLTRIM(cCOID) AND !DELETED()
FOUND()
	REPLACE ORDRSTAT.SP_TYPE WITH "No Change"
	REPLACE ORDRSTAT.SP_ADDR1 WITH SLINEONE
	REPLACE ORDRSTAT.SP_ADDR2 WITH SLINETWO
	REPLACE ORDRSTAT.SP_CITY WITH SCITY
	REPLACE ORDRSTAT.SP_STATE WITH SSTATE
	REPLACE ORDRSTAT.SP_ZIP WITH SZIP
	REPLACE ORDRSTAT.SP_COUNTRY WITH SCOUNTRY
	REPLACE ORDRSTAT.SP_AREACD WITH SAREA
	REPLACE ORDRSTAT.SP_PHONE WITH SPHONE
	REPLACE ORDRSTAT.SP_ATTN WITH SATTN

	REPLACE ORDRSTAT.B_TYPE WITH "No Change"
	REPLACE ORDRSTAT.B_ADDR1 WITH BLINEONE
	REPLACE ORDRSTAT.B_ADDR2 WITH BLINETWO
	REPLACE ORDRSTAT.B_CITY WITH BCITY
	REPLACE ORDRSTAT.B_STATE WITH BSTATE
	REPLACE ORDRSTAT.B_ZIP WITH BZIP
	REPLACE ORDRSTAT.B_COUNTRY WITH BCOUNTRY
	REPLACE ORDRSTAT.B_AREACD WITH BAREA
	REPLACE ORDRSTAT.B_PHONE WITH BPHONE
	REPLACE ORDRSTAT.B_ATTN WITH BATTN
	

	IF !EMPTY(cQUOTENO)
				

			SELECT quote_header  
			LOCATE FOR ALLTRIM(quote_no) == ALLTRIM(cQUOTENO) AND NOT DELETED()
			Found = FOUND()
			STORE ship_via TO shipvia
			STORE from TO takenby
			STORE frst_name TO firstname
			STORE last_name TO lastname
			STORE area_code TO areacode
			STORE phone_no TO phoneno
			STORE sub_total TO subtotal
			STORE ref_no TO po_num
			STORE freight TO frght
			STORE taxes TO tx
			STORE total TO ttl	
			STORE tax_rate TO tx_rate
			REPLACE new_order WITH cORDERNO
			
			SELECT ordrstat
			LOCATE FOR ALLTRIM(order_no) == ALLTRIM(cORDERNO) AND !DELETED()
			FOUND = FOUND()
			Replace ship_via WITH  shipvia
			Replace taken_by WITH LEFT(takenby, 1) + SUBSTR(takenby, AT(" ", takenby) + 1, 1)
			REPLACE po_no WITH po_num
			REPLACE placed_by WITH ALLTRIM(firstname) + " " + ALLTRIM(lastname)
			REPLACE pb_area WITH areacode
			REPLACE pb_phone WITH phoneno
			REPLACE sub_total WITH subtotal
			REPLACE freight WITH frght
			REPLACE tax_rate WITH tx_rate
			REPLACE taxes WITH tx
			REPLACE total WITH ttl - frght 
			REPLACE end_total WITH subtotal + tx + frght
				
				
			SELECT quote_detail
			SET ORDER TO 4	
			
			SCAN FOR ALLTRIM(quote_no) == ALLTRIM(cQUOTENO) AND NOT DELETED()
				
				SELECT quote_detail
				STORE entry_no TO entryno
				STORE part TO cPart
				STORE quant TO nQuant	
				STORE descrption TO Description
				STORE taxable to tax
				STORE cost TO nCost
				STORE total_cost TO nTotal_cost
				STORE custom TO cCustom	
				STORE acct_num TO cAcctNum
				REPLACE new_order WITH cORDERNO
						
				SELECT order_de	
				SCATTER NAME oOrder_de BLANK 
				oOrder_de.co_id = cCOID
				oOrder_de.order_no = corderno
				oOrder_de.entry_no = entryno
				oOrder_de.part = cPart
				oOrder_de.quant = nQuant
				oOrder_de.descript = Description
				oOrder_de.taxable = tax
				oOrder_de.cost = nCost
				oOrder_de.total_cost = nTotal_cost
				oOrder_de.custom = cCustom
				oOrder_de.acct_num = cAcctNum
						
				APPEND BLANK
				GATHER NAME oOrder_de
				
				IF !EMPTY(cCustom)
					SELECT CUSTOM
					APPEND BLANK 
					REPLACE CO_ID WITH CONO
				   	REPLACE ORDER_NO WITH cORDERNO
				   	REPLACE DESCRIPT WITH DESCRIPTION
				   	REPLACE PART_NO WITH cPART
				   	REPLACE CUSTOM WITH cCUSTOM
				   	REPLACE COST WITH nCOST
				   	SELECT ORDER_DE
				ENDIF	
				RELEASE oOrder_de
				
			ENDSCAN 	
			
			MESSAGEBOX('ORDER # '+ ALLTRIM(CORDERNO), 0, "Quote Successfully Converted to Order")
	ENDIF
	
	SELECT ordrstat
	LOCATE FOR ALLTRIM(order_no) == cORDERNO AND ALLTRIM(co_id) == cCOID AND !DELETED()

ENDPROC 



	
	


