
PROCEDURE GET_PART
	PUBLIC ALLOWEDIT
	PUBLIC TAXBL
	PUBLIC PARTACCT
	 	 	
 	SELECT 4
 	STORE PART_NO TO PARTNO
	STORE PRICE_EACH TO PRICE
	STORE DESCRPTION TO DESCRIPTION
	STORE 0 TO QUANT
	STORE ALLOW_EDIT TO ALLOWEDIT
	STORE TAXABLE TO TAXBL
	STORE ACCT_NUM TO PARTACCT
	
	
	USE
	SELECT 5
	DEACTIVATE WINDOW BIG

	IF LEFT(PARTNO, 6)="CUSTOM"
		CUSTITEM=1
	ENDIF
	IF PARTNO="MISC"
		CUSTITEM=1
	ENDIF
	IF PARTNO="RETURN-PART"
		CUSTITEM=1
	ENDIF
	IF PARTNO="FREIGHT"
		CUSTITEM=1
	ENDIF

	SELECT 5
	LOCATE FOR QUOTE_NO = QUOTENO

	IF PARTNO = "??"
		PARTNO=""
	ENDIF
	
ENDPROC
	
PROCEDURE GET_DESCRIPTION
 	ON KEY LABEL F2 DO DONE
 	SELECT 4
 	STORE PART_NO TO PARTNO
	STORE DESCRPTION TO DESCRIPTION
	STORE PRICE_EACH TO PRICE
	STORE 0 TO QUANT
	STORE ALLOW_EDIT TO ALLOWEDIT
	STORE TAXABLE TO TAXBL
	STORE ACCT_NUM TO PARTACCT
	
	
	USE 
	SELECT 5
	DEACTIVATE WINDOW BIG
	
	IF LEFT(PARTNO, 6)="CUSTOM"
		CUSTITEM=1
	ENDIF
	IF PARTNO="MISC"
		CUSTITEM=1
	ENDIF
	IF PARTNO="RETURN-PART"
		CUSTITEM=1
	ENDIF
	IF PARTNO="FREIGHT"
		CUSTITEM=1
	ENDIF

	SELECT 5
	LOCATE FOR QUOTE_NO = QUOTENO

	IF DESCRIPTION="??"
		DESCRIPTION=""
	ENDIF
	

PROCEDURE ADD_ITEM

		IF CUSTITEM=1	
		    CUST="YES"
		    PATH=""
			DO PATH.PRG
			USE PATH+"CUSTOM_I" IN 20 			
			NEXT_ID=""
			THIS_ID=0
			NEXT_NUMBER=0
			ZEROS=""
			NZEROS=0
			SELECT CUSTOM_I
			STORE CUST_ID TO THIS_ID
			NEXT_ID="000000"+ALLTRIM(STR(THIS_ID))
			NEXT_ID=RIGHT(ALLTRIM(NEXT_ID), 7)
			NEXT_NUMBER=THIS_ID + 1
			REPLACE CUST_ID WITH NEXT_NUMBER
		ELSE
		    CUST="NO"
 		   	NEXT_ID=""
		ENDIF
		

		SELECT 5
		SET ORDER TO QUOTENTRY  && QUOTE_NO+STR(ENTRY_NO)
		SCAN FOR QUOTE_NO = QUOTENO
			STORE ENTRY_NO TO ENTRY
		ENDSCAN
		
		ENTRY=ENTRY+1	

		SELECT 5
		   APPEND BLANK
		   REPLACE ENTRY_NO WITH ENTRY
 		   REPLACE CO_ID WITH COID
		   REPLACE CO_NAME WITH CONAME
		   REPLACE QUOTE_NO WITH QUOTENO
		   REPLACE PART WITH PARTNO
		   REPLACE COST WITH PRICE
		   REPLACE QUANT WITH QUANTITY
		   REPLACE DESCRPTION WITH DESCRIPTION
		   REPLACE TOTAL_COST WITH TCOST
		   REPLACE CUSTOM WITH NEXT_ID
		  		  
		    ORDACCT="N/A"	
		  
		  	IF PARTACCT = "3023"
				ORDACCT = SALES+" 3023"
				TAXBL="N"
			ELSE
				IF TAX_CD = "01"
					ORDACCT = "3020 3021"
					TAXBL="Y"
				ELSE
					IF PARTACCT = ""
						ORDACCT = SALES+" "+SALE_SUB
					ELSE
						ORDACCT = PARTACCT
					ENDIF
					TAXBL="N"
				ENDIF
			ENDIF		 		   
		    
		   REPLACE ACCT_NUM WITH ORDACCT
		   REPLACE TAXABLE WITH TAXBL
		  		   
		   GOTO TOP

		   PARTNO=""
		   DESCRIPTION=""
		   QUANTITY=0.00
		   PRICE = 0.00
		   TCOST = 0.00			


ENDPROC	



