SET DEFAULT TO C:\FOXAPPS2\FOXAPP\SHRTRIDG

ON KEY LABEL F12 DO STARTUP.PRG
ON ERROR DO ERR_FIX.PRG

SET EXCLUSIVE OFF
SET BELL OFF
CLEAR PROGRAM
CLEAR
CLOSE ALL
SET TALK OFF

DEFINE WINDOW HIDECOM FROM 1,1 TO 3,3
ACTIVATE WINDOW COMMAND IN HIDECOM
DO BETSY.MPR


PROCEDURE NOESCAPE
	ESCAPE=""
ENDPROC