SYS(3050,1,VAL(SYS(1001)))

SET DEFAULT TO W:\FOXAPPS\
OPEN DATABASE W:\FOXAPPS\SHORTDATA SHARED

**DO w:\foxapps\tbsave.prg
*DO TBSAVE.PRG


** SET ESCAPE OFF **
** DISABLE EXIT HOTKEY **
ON KEY LABEL ESCAPE DO NOESCAPE
* IN SHRTRIDG\FOXPRO.PRG
ON KEY LABEL ALT+E DO NOEXIT 
*IN SHRTRIDG\FOXPRO.PRG

** SHOW ERROR MESSAGE ON ERRORS **
ON ERROR DO W:\FOXAPPS\SHRTRIDG\ERR_FIX

** SET DEFAULT SETTINGS **
SET EXCLUSIVE OFF
SET BELL OFF
SET TALK OFF
SET RESOURCE OFF 



	

KEYBOARD '{ALT+H}'

DO CALIBRATION\CALIBRATION.MPR
*READ EVENTS

KEYBOARD '{ALT+H}'   

SET SKIP OF PAD Hide OF _MSYSMENU .T.

PROCEDURE NOESCAPE
   ESCAPE=""
ENDPROC  

PROCEDURE NOEXIT
	RETURN
ENDPROC 
   
