SYS(3050,1,VAL(SYS(1001)))

PUBLIC cMENU

SET EXCLUSIVE off
OPEN DATABASE W:\FOXAPPS\SHORTDATA shared
SET DEFAULT TO W:\FOXAPPS\

DO Supervisor\TBSAVE.PRG
** SET ESCAPE OFF **
*ON KEY LABEL ESCAPE DO NOESCAPE IN SUPERVISOR.PRG

*ON KEY LABEL ALT+E DO NOEXIT IN SUPERVISOR.PRG

** SHOW ERROR MESSAGE ON ERRORS **
ON ERROR DO W:\FOXAPPS\SHRTRIDG\ERR_FIX
cMENU = "SUPERVISOR"

** SET DEFAULT SETTINGS **
SET EXCLUSIVE OFF
SET BELL OFF
SET TALK OFF


KEYBOARD '{ALT+H}'

DO SUPERVISOR\SUPERVISOR.MPR


PROCEDURE NOESCAPE
   ESCAPE=""
   
PROCEDURE NOEXIT
	RETURN   
   
KEYBOARD '{ALT+H}'   