CLOSE ALL
OPEN DATABASE W:\FOXAPPS\SHORTDATA
DIMENSION CONTACT_ID_ARRAY(1)




USE COMPANY
COPY TO MAILING_LIST FIELDS CO_ID, CO_NAME, S_ADDR1, S_ADDR2, S_CITY, S_STATE, S_ZIP, S_COUNTRY FOR QA_REQ <>  "94" AND  BUS_TYPE <> "5084" AND BUS_TYPE <> "8734"  

USE contact IN 2 SHARED 

USE MAILING_LIST IN 1 EXCLUSIVE
ALTER TABLE MAILING_LIST ADD COLUMN FRST_NAME CHAR(22) NULL
ALTER TABLE MAILING_LIST ADD COLUMN LAST_NAME CHAR(13) NULL
ALTER TABLE MAILING_LIST ADD COLUMN TITLE CHAR(24) NULL
ALTER TABLE MAILING_LIST ADD COLUMN EMAIL CHAR(50) NULL

SET EXACT ON

DELETE FROM MAILING_LIST WHERE CO_ID IN (SELECT CO_ID FROM MODEL_NO WHERE MAILING_LIST.CO_ID = MODEL_NO.CO_ID AND;
 (ALLTRIM(MODEL_NO) == "88-860C" OR ;
 ALLTRIM(MODEL_NO) == "850-860C" OR ;
 ALLTRIM(MODEL_NO) == "860-860C" OR ; 
 ALLTRIM(MODEL_NO) ==  "88-870C" OR ;
 ALLTRIM(MODEL_NO) == "850-870C" OR ;
 ALLTRIM(MODEL_NO) == "860-870C" OR ;
 ALLTRIM(MODEL_NO) == "870-870C"))

DELETE FROM MAILING_LIST WHERE CO_ID NOT IN ;
(SELECT CO_ID FROM MODEL_NO WHERE MAILING_LIST.CO_ID = MODEL_NO.CO_ID AND CAL_DATE >= CTOD("1/1/2000") AND ;
(ALLTRIM(MODEL_NO) == "RECAL-860" OR ;
 ALLTRIM(MODEL_NO) == "RECAL-870" OR ;
 ALLTRIM(MODEL_NO) == "ADM-860" OR ;
 ALLTRIM(MODEL_NO) == "ADM-870")) 

PACK
SET EXACT OFF

N = 0

USE mailing_list
SCAN
	
	contact_id_array = 0
	
	SELECT MAX(contact_id) FROM contact WHERE contact.co_id = mailing_list.co_id AND DATE_MODIFIED = (SELECT MAX(DATE_MODIFIED) FROM CONTACT WHERE CONTACT.CO_ID = MAILING_LIST.CO_ID AND !EMPTY(DATE_MODIFIED)) INTO ARRAY contact_id_array
	
	IF contact_id_array = 0
		
		SELECT MAX(contact_id) FROM contact WHERE contact.co_id = mailing_list.co_id AND DATE_ENTERED = (SELECT MAX(DATE_ENTERED) FROM CONTACT WHERE CONTACT.CO_ID = MAILING_LIST.CO_ID AND !EMPTY(DATE_ENTERED)) INTO ARRAY contact_id_array
		
		IF contact_id_array = 0
			SELECT MAX(contact_id) FROM contact WHERE contact.co_id = mailing_list.co_id INTO ARRAY CONTACT_ID_ARRAY
		ENDIF
	ENDIF


	IF contact_id_array <> 0
		SELECT 2
		LOCATE FOR CONTACT_ID = CONTACT_ID_ARRAY
		STORE FRST_NAME TO FIRSTNAME
		STORE LAST_NAME TO LASTNAME
		STORE TITLE TO CONTACTTITLE
		STORE EMAIL TO CONTACTEMAIL		
		
		SELECT 1
		REPLACE FRST_NAME WITH FIRSTNAME
		REPLACE LAST_NAME WITH LASTNAME
		REPLACE TITLE WITH CONTACTTITLE
		REPLACE EMAIL WITH CONTACTEMAIL
	ENDIF

	N = N + 1
ENDSCAN

MESSAGEBOX(STR(N) + " COMPANY RECORDS SELECTED.  EXCEL FILE COPIED TO W:\FOXAPPS\MAILING_LIST.XLS.")

COPY TO "W:\Foxapps\MAILING_LIST.XLS" DELIMITED WITH TAB






