// <auto-generated />
using System;
using CalibrationManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CalibrationManagement.Infrastructure.Migrations
{
    [DbContext(typeof(CalibrationDbContext))]
    partial class CalibrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CalibrationManagement.Core.Entities.CalData", b =>
                {
                    b.Property<Guid>("CalDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cal_data_id");

                    b.Property<decimal?>("ActualReading")
                        .HasPrecision(15, 6)
                        .HasColumnType("numeric(15,6)")
                        .HasColumnName("actual_reading");

                    b.Property<Guid>("CalId")
                        .HasColumnType("uuid")
                        .HasColumnName("cal_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<decimal?>("Deviation")
                        .HasPrecision(15, 6)
                        .HasColumnType("numeric(15,6)")
                        .HasColumnName("deviation");

                    b.Property<string>("Mode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mode");

                    b.Property<string>("PassFail")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pass_fail");

                    b.Property<decimal?>("PercentDeviation")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)")
                        .HasColumnName("percent_deviation");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_no");

                    b.Property<decimal?>("SetPoint")
                        .HasPrecision(15, 6)
                        .HasColumnType("numeric(15,6)")
                        .HasColumnName("set_point");

                    b.Property<decimal?>("Tolerance")
                        .HasPrecision(15, 6)
                        .HasColumnType("numeric(15,6)")
                        .HasColumnName("tolerance");

                    b.Property<string>("Units")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("units");

                    b.HasKey("CalDataId");

                    b.HasIndex("CalId");

                    b.ToTable("cal_data");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.CalInfo", b =>
                {
                    b.Property<Guid>("CalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cal_id");

                    b.Property<DateTime?>("CalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cal_date");

                    b.Property<string>("CalNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cal_no");

                    b.Property<string>("CalStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cal_status");

                    b.Property<string>("CalTech")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cal_tech");

                    b.Property<string>("CalType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cal_type");

                    b.Property<string>("CoId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("co_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<decimal?>("Humidity")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("humidity");

                    b.Property<string>("ModelNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_no");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OrderNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_no");

                    b.Property<decimal?>("Pressure")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("pressure");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_no");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("temperature");

                    b.HasKey("CalId");

                    b.HasIndex("CalDate");

                    b.HasIndex("CalNo")
                        .IsUnique()
                        .HasDatabaseName("IX_cal_info_cal_no_unique");

                    b.HasIndex("CalType");

                    b.HasIndex("CoId");

                    b.HasIndex("DueDate");

                    b.HasIndex("SerialNo");

                    b.ToTable("cal_info");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.CalSetup", b =>
                {
                    b.Property<Guid>("CalSetupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cal_setup_id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("CalStd")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cal_std");

                    b.Property<string>("CalStd2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cal_std2");

                    b.Property<string>("CalType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cal_type");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<string>("Mode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mode");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("CalSetupId");

                    b.ToTable("cal_setup");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.CalStandards", b =>
                {
                    b.Property<Guid>("CalStdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cal_std_id");

                    b.Property<Guid>("CalId")
                        .HasColumnType("uuid")
                        .HasColumnName("cal_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("StdCalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("std_cal_date");

                    b.Property<DateTime?>("StdDueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("std_due_date");

                    b.Property<string>("StdModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("std_model");

                    b.Property<string>("StdSerialNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("std_serial_no");

                    b.Property<string>("StdType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("std_type");

                    b.Property<decimal?>("StdUncertainty")
                        .HasPrecision(15, 6)
                        .HasColumnType("numeric(15,6)")
                        .HasColumnName("std_uncertainty");

                    b.HasKey("CalStdId");

                    b.HasIndex("CalId");

                    b.ToTable("cal_standards");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.CalTechs", b =>
                {
                    b.Property<Guid>("CalTechId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cal_tech_id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<string>("TechInitials")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tech_initials");

                    b.Property<string>("TechName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tech_name");

                    b.HasKey("CalTechId");

                    b.ToTable("cal_techs");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Address1")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address2");

                    b.Property<decimal?>("Balance")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("balance");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("city");

                    b.Property<string>("CoId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("co_id");

                    b.Property<string>("CoName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("co_name");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<decimal?>("CreditLimit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("credit_limit");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<string>("DiscountCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("discount_code");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Fax")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("fax");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("State")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("state");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_id");

                    b.Property<string>("Terms")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("terms");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("website");

                    b.Property<string>("Zip")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zip");

                    b.HasKey("CompanyId");

                    b.HasIndex("CoId")
                        .IsUnique()
                        .HasDatabaseName("IX_company_co_id_unique");

                    b.HasIndex("CoName");

                    b.ToTable("company");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.Contact", b =>
                {
                    b.Property<Guid>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("CoId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("co_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<bool>("PrimaryContact")
                        .HasColumnType("boolean")
                        .HasColumnName("primary_contact");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("ContactId");

                    b.HasIndex("CoId");

                    b.ToTable("contact");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<decimal?>("Balance")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("balance");

                    b.Property<string>("CoId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("co_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<DateTime?>("InvDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inv_date");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_no");

                    b.Property<string>("OrderNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_no");

                    b.Property<decimal?>("PaidAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("paid_amount");

                    b.Property<string>("QaCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("qa_code");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal?>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal?>("TaxAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CoId");

                    b.HasIndex("InvoiceNo")
                        .IsUnique()
                        .HasDatabaseName("IX_invoice_invoice_no_unique");

                    b.ToTable("invoice");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.ModelNo", b =>
                {
                    b.Property<Guid>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<DateTime?>("CalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cal_date");

                    b.Property<string>("CalType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cal_type");

                    b.Property<string>("CoId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("co_id");

                    b.Property<string>("CoName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("co_name");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("ModelNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_no");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("OrderNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_no");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_no");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("ModelId");

                    b.HasIndex("CoId");

                    b.HasIndex("SerialNo")
                        .IsUnique()
                        .HasDatabaseName("IX_model_no_serial_no_unique");

                    b.ToTable("model_no");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.OrDetail", b =>
                {
                    b.Property<Guid>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("order_detail_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("ExtendedPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("extended_price");

                    b.Property<int?>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<string>("OrderNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_no");

                    b.Property<string>("PartNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_no");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderNo");

                    b.ToTable("ordetail");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.OrdrStat", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("CoId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("co_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_date");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_no");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("OrderId");

                    b.HasIndex("CoId");

                    b.HasIndex("OrderNo")
                        .IsUnique()
                        .HasDatabaseName("IX_ordrstat_order_no_unique");

                    b.ToTable("ordrstat");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.PayDtl", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("CheckNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("check_no");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_no");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("PaymentAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("payment_amount");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceNo");

                    b.ToTable("pay_dtl");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.Tolerances", b =>
                {
                    b.Property<Guid>("ToleranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tolerance_id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("CalType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cal_type");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<decimal?>("RangeMax")
                        .HasPrecision(15, 6)
                        .HasColumnType("numeric(15,6)")
                        .HasColumnName("range_max");

                    b.Property<decimal?>("RangeMin")
                        .HasPrecision(15, 6)
                        .HasColumnType("numeric(15,6)")
                        .HasColumnName("range_min");

                    b.Property<string>("ToleranceType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tolerance_type");

                    b.Property<decimal?>("ToleranceValue")
                        .HasPrecision(15, 6)
                        .HasColumnType("numeric(15,6)")
                        .HasColumnName("tolerance_value");

                    b.Property<string>("Units")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("units");

                    b.HasKey("ToleranceId");

                    b.ToTable("tolerances");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_users_username_unique");

                    b.ToTable("users");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.CalData", b =>
                {
                    b.HasOne("CalibrationManagement.Core.Entities.CalInfo", "CalInfo")
                        .WithMany("CalData")
                        .HasForeignKey("CalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalInfo");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.CalInfo", b =>
                {
                    b.HasOne("CalibrationManagement.Core.Entities.Company", "Company")
                        .WithMany("CalInfos")
                        .HasForeignKey("CoId")
                        .HasPrincipalKey("CoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.CalStandards", b =>
                {
                    b.HasOne("CalibrationManagement.Core.Entities.CalInfo", "CalInfo")
                        .WithMany("CalStandards")
                        .HasForeignKey("CalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalInfo");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.Contact", b =>
                {
                    b.HasOne("CalibrationManagement.Core.Entities.Company", "Company")
                        .WithMany("Contacts")
                        .HasForeignKey("CoId")
                        .HasPrincipalKey("CoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.Invoice", b =>
                {
                    b.HasOne("CalibrationManagement.Core.Entities.Company", "Company")
                        .WithMany("Invoices")
                        .HasForeignKey("CoId")
                        .HasPrincipalKey("CoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.ModelNo", b =>
                {
                    b.HasOne("CalibrationManagement.Core.Entities.Company", "Company")
                        .WithMany("ModelNumbers")
                        .HasForeignKey("CoId")
                        .HasPrincipalKey("CoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.OrDetail", b =>
                {
                    b.HasOne("CalibrationManagement.Core.Entities.OrdrStat", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderNo")
                        .HasPrincipalKey("OrderNo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.OrdrStat", b =>
                {
                    b.HasOne("CalibrationManagement.Core.Entities.Company", "Company")
                        .WithMany("Orders")
                        .HasForeignKey("CoId")
                        .HasPrincipalKey("CoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.PayDtl", b =>
                {
                    b.HasOne("CalibrationManagement.Core.Entities.Invoice", "Invoice")
                        .WithMany("PaymentDetails")
                        .HasForeignKey("InvoiceNo")
                        .HasPrincipalKey("InvoiceNo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.CalInfo", b =>
                {
                    b.Navigation("CalData");

                    b.Navigation("CalStandards");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.Company", b =>
                {
                    b.Navigation("CalInfos");

                    b.Navigation("Contacts");

                    b.Navigation("Invoices");

                    b.Navigation("ModelNumbers");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.Invoice", b =>
                {
                    b.Navigation("PaymentDetails");
                });

            modelBuilder.Entity("CalibrationManagement.Core.Entities.OrdrStat", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
